version: '3'
services:
  neo4j:
    image: neo4j:4.4
    container_name: neo4j
    ports:
      - "7687:7687"
      - "7474:7474"
    environment:
      NEO4J_AUTH: "neo4j/B6jh8J7OL0"
    volumes:
      - "/home/miguel/.config/Neo4j\ Destkop/Application/relate-data/dbmss/dbms-e5cf6b54-7044-4f66-9555-f0003a01d8a3/data:/data"
      - "/home/miguel/.config/Neo4j\ Destkop/Application/relate-data/dbmss/dbms-e5cf6b54-7044-4f66-9555-f0003a01d8a3/conf:/conf"
      - "/home/miguel/.config/Neo4j\ Destkop/Application/relate-data/dbmss/dbms-e5cf6b54-7044-4f66-9555-f0003a01d8a3/logs:/logs"
      - "/home/miguel/.config/Neo4j\ Destkop/Application/relate-data/dbmss/dbms-e5cf6b54-7044-4f66-9555-f0003a01d8a3/plugins:/plugins"

  api:
    build: .
    container_name: api
    ports:
      - "3000:3000"
    depends_on:
      - neo4j
    environment:
      NEO4J_URI: "bolt://neo4j:7687"
      NEO4J_USER: "neo4j"
      NEO4J_PASSWORD: "B6jh8J7OL0"

  frontend:
    build:
      context: ./front-end
    container_name: frontend
    ports:
      - "4200:4200"
    depends_on:
      - api
